/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'index___fa': RouteRecordInfo<'index___fa', '/', Record<never, never>, Record<never, never>>,
    'slug___fa': RouteRecordInfo<'slug___fa', '/:slug(.*)*', { slug?: ParamValueZeroOrMore<true> }, { slug?: ParamValueZeroOrMore<false> }>,
    'about___fa': RouteRecordInfo<'about___fa', '/about', Record<never, never>, Record<never, never>>,
    'Data___fa': RouteRecordInfo<'Data___fa', '/Data', Record<never, never>, Record<never, never>>,
    'index___en': RouteRecordInfo<'index___en', '/en', Record<never, never>, Record<never, never>>,
    'slug___en': RouteRecordInfo<'slug___en', '/en/:slug(.*)*', { slug?: ParamValueZeroOrMore<true> }, { slug?: ParamValueZeroOrMore<false> }>,
    'about___en': RouteRecordInfo<'about___en', '/en/about', Record<never, never>, Record<never, never>>,
    'Data___en': RouteRecordInfo<'Data___en', '/en/Data', Record<never, never>, Record<never, never>>,
    'grants___en': RouteRecordInfo<'grants___en', '/en/grants', Record<never, never>, Record<never, never>>,
    'Legal___en': RouteRecordInfo<'Legal___en', '/en/Legal', Record<never, never>, Record<never, never>>,
    'news___en': RouteRecordInfo<'news___en', '/en/news', Record<never, never>, Record<never, never>>,
    'resources___en': RouteRecordInfo<'resources___en', '/en/resources', Record<never, never>, Record<never, never>>,
    'roadmap___en': RouteRecordInfo<'roadmap___en', '/en/roadmap', Record<never, never>, Record<never, never>>,
    'sample___en': RouteRecordInfo<'sample___en', '/en/sample', Record<never, never>, Record<never, never>>,
    'index___fr': RouteRecordInfo<'index___fr', '/fr', Record<never, never>, Record<never, never>>,
    'slug___fr': RouteRecordInfo<'slug___fr', '/fr/:slug(.*)*', { slug?: ParamValueZeroOrMore<true> }, { slug?: ParamValueZeroOrMore<false> }>,
    'about___fr': RouteRecordInfo<'about___fr', '/fr/about', Record<never, never>, Record<never, never>>,
    'Data___fr': RouteRecordInfo<'Data___fr', '/fr/Data', Record<never, never>, Record<never, never>>,
    'grants___fr': RouteRecordInfo<'grants___fr', '/fr/grants', Record<never, never>, Record<never, never>>,
    'Legal___fr': RouteRecordInfo<'Legal___fr', '/fr/Legal', Record<never, never>, Record<never, never>>,
    'news___fr': RouteRecordInfo<'news___fr', '/fr/news', Record<never, never>, Record<never, never>>,
    'resources___fr': RouteRecordInfo<'resources___fr', '/fr/resources', Record<never, never>, Record<never, never>>,
    'roadmap___fr': RouteRecordInfo<'roadmap___fr', '/fr/roadmap', Record<never, never>, Record<never, never>>,
    'sample___fr': RouteRecordInfo<'sample___fr', '/fr/sample', Record<never, never>, Record<never, never>>,
    'grants___fa': RouteRecordInfo<'grants___fa', '/grants', Record<never, never>, Record<never, never>>,
    'index___jp': RouteRecordInfo<'index___jp', '/jp', Record<never, never>, Record<never, never>>,
    'slug___jp': RouteRecordInfo<'slug___jp', '/jp/:slug(.*)*', { slug?: ParamValueZeroOrMore<true> }, { slug?: ParamValueZeroOrMore<false> }>,
    'about___jp': RouteRecordInfo<'about___jp', '/jp/about', Record<never, never>, Record<never, never>>,
    'Data___jp': RouteRecordInfo<'Data___jp', '/jp/Data', Record<never, never>, Record<never, never>>,
    'grants___jp': RouteRecordInfo<'grants___jp', '/jp/grants', Record<never, never>, Record<never, never>>,
    'Legal___jp': RouteRecordInfo<'Legal___jp', '/jp/Legal', Record<never, never>, Record<never, never>>,
    'news___jp': RouteRecordInfo<'news___jp', '/jp/news', Record<never, never>, Record<never, never>>,
    'resources___jp': RouteRecordInfo<'resources___jp', '/jp/resources', Record<never, never>, Record<never, never>>,
    'roadmap___jp': RouteRecordInfo<'roadmap___jp', '/jp/roadmap', Record<never, never>, Record<never, never>>,
    'sample___jp': RouteRecordInfo<'sample___jp', '/jp/sample', Record<never, never>, Record<never, never>>,
    'Legal___fa': RouteRecordInfo<'Legal___fa', '/Legal', Record<never, never>, Record<never, never>>,
    'news___fa': RouteRecordInfo<'news___fa', '/news', Record<never, never>, Record<never, never>>,
    'resources___fa': RouteRecordInfo<'resources___fa', '/resources', Record<never, never>, Record<never, never>>,
    'roadmap___fa': RouteRecordInfo<'roadmap___fa', '/roadmap', Record<never, never>, Record<never, never>>,
    'sample___fa': RouteRecordInfo<'sample___fa', '/sample', Record<never, never>, Record<never, never>>,
  }
}
